version: "2"

services:
  logstash-xpack:
    image: elbaschid/datadog-logstash-drain:xpack
    build: ./logstash
    volumes:
      - "./logstash/pipeline:/usr/share/logstash/pipeline/"
    command: logstash --config.debug
  logstash-oss:
    image: elbaschid/datadog-logstash-drain:oss
    build: ./logstash-oss/
    volumes:
      - "./logstash-oss/pipeline:/usr/share/logstash/pipeline/"
    command: logstash --config.debug
